spring:
  application:
    name: yara-app-userprofile
  jpa:
    hibernate:
      ddl-auto:  create
server:
  port: 8081
mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/yara-app_user
    username: root
    password: admin