spring:
  application:
    name: amcart-infra-apigateway
zuul:
  ignoredServices: '*'
  routes:
    amcart-userprofile: /profile/**
    amcart-ordermanagement: /order/**
    amcart-inventory: /inventory/**
