spring:
  application:
    name: amcart-notifications
  rabbitmq:
    host: localhost
server:
  port: 8084
notifications:
  email:
    from:
      address:
      password: 
    smtp: smtp.gmail.com
    port: 587
mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/amcart_notification
    username: root
    password: 
infra:
  gateway:
    host: localhost
    port:  8083
profile:
  service:
    mapping: /profile
    getUsersByIdsMapping: /users/getUsersByIds/     